name: 'Pipelab'
description: 'Run Pipelab projects'
inputs:
  action:
    description: 'What action to run' # run | validate
    required: true
  project:
    description: 'The path to a project file'
    required: true
  pipelab-version:
    description: 'The version of Pipelab to use'
    required: true
outputs:
  code:
    description: 'The exit code returned by the app'
  error:
    description: 'The exit error returned by the app'
runs:
  using: 'node20'
  main: 'dist/index.js'
